version: '3.8'
services:
  api:
    image: python:3.10-slim
    container_name: eeg_api
    working_dir: /app
    volumes:
      - ./:/app
    command: uvicorn api_cupynumeric_db:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=sqlite:///./eeg_data.db
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  # Опционально: pgadmin или другие сервисы

volumes:
  db_data:
    driver: local